version: "3.9"

services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    ports:
      - "8080:8080"
    environment:
      - GATUS_CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml:ro
    restart: unless-stopped
