FROM twinproduction/gatus:v5.21.0

COPY config.yaml /config/config.yaml

EXPOSE 8080

CMD ["--config-file", "/config/config.yaml"]

# Updated Mon Aug 18 16:47:31 BST 2025
# Updated Mon Aug 18 16:51:39 BST 2025
# Updated Mon Aug 18 19:32:20 BST 2025
# Updated Mon Aug 18 19:35:58 BST 2025
# Updated Mon Aug 18 19:38:53 BST 2025
# Updated Mon Aug 18 19:56:50 BST 2025
