name: Security Scan & Plan

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'terraform/**'
      - 'Docker/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'Docker/**'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform
          soft_fail: false

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          soft_fail: false

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        working-directory: ./terraform
        run: tflint --recursive

      - name: Terraform plan
        working-directory: ./terraform
        env:
          TF_VAR_vpc_id: ${{ secrets.TF_VAR_VPC_ID }}
          TF_VAR_subnets_id_list: ${{ secrets.TF_VAR_SUBNETS_ID_LIST }}
          TF_VAR_image_url: "016873651140.dkr.ecr.eu-west-2.amazonaws.com/gatus-project:latest"
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json

      - name: Upload plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform/plan.json
          retention-days: 30

      - name: Lint Dockerfile
        if: contains(github.event.head_commit.modified, 'Docker/') || github.event_name == 'pull_request'
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
          hadolint Docker/Dockerfile

2. Fix build.yml:
bashcat > .github/workflows/build.yml << 'EOF'
name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Docker/**'
      - 'terraform/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-12)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gatus-project:${{ steps.vars.outputs.IMAGE_TAG }} \
                       -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gatus-project:latest \
                       -f ./Docker/Dockerfile ./Docker

      - name: Cache Trivy DB
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-v1

      - name: Install Trivy
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz
          tar zxvf trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy security scan
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        run: |
          trivy image --exit-code 1 --no-progress --severity HIGH,CRITICAL \
             ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gatus-project:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Push Docker images
        if: contains(github.event.head_commit.modified, 'Docker/') || contains(github.event.head_commit.added, 'Docker/')
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gatus-project:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gatus-project:latest

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Resolve deployment image
        id: image
        run: |
          ACCOUNT="${{ secrets.AWS_ACCOUNT_ID }}"
          REGION="${{ secrets.AWS_REGION }}"
          REPO="gatus-project"
          
          if [[ "${{ github.event.head_commit.modified }}" == *"Docker/"* ]] || [[ "${{ github.event.head_commit.added }}" == *"Docker/"* ]]; then
            IMAGE_URI="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO:${{ steps.vars.outputs.IMAGE_TAG }}"
            echo "Deploying newly built image: ${{ steps.vars.outputs.IMAGE_TAG }}"
          else
            DIGEST=$(aws ecr describe-images \
              --repository-name "$REPO" \
              --query 'reverse(sort_by(imageDetails,& imagePushedAt))[0].imageDigest' \
              --output text)
            IMAGE_URI="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO@$DIGEST"
            echo "Using existing latest image for terraform changes"
          fi

          echo "IMAGE_URI=$IMAGE_URI" >> "$GITHUB_OUTPUT"

      - name: Terraform plan
        working-directory: ./terraform
        env:
          TF_VAR_vpc_id: ${{ secrets.TF_VAR_VPC_ID }}
          TF_VAR_subnets_id_list: ${{ secrets.TF_VAR_SUBNETS_ID_LIST }}
          TF_VAR_image_url: ${{ steps.image.outputs.IMAGE_URI }}
        run: terraform plan -out=tfplan

      - name: Terraform apply
        working-directory: ./terraform
        env:
          TF_VAR_vpc_id: ${{ secrets.TF_VAR_VPC_ID }}
          TF_VAR_subnets_id_list: ${{ secrets.TF_VAR_SUBNETS_ID_LIST }}
          TF_VAR_image_url: ${{ steps.image.outputs.IMAGE_URI }}
        run: terraform apply tfplan

      - name: Wait for ECS service stability
        run: |
          echo "Waiting for ECS service to stabilize..."
          aws ecs wait services-stable --cluster gatus-cluster --services gatus-service

      - name: Deployment summary
        run: |
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster gatus-cluster \
            --services gatus-service \
            --query 'services[0].status' \
            --output text)

          RUNNING_COUNT=$(aws ecs describe-services \
            --cluster gatus-cluster \
            --services gatus-service \
            --query 'services[0].runningCount' \
            --output text)

          echo "Deployment Summary:"
          echo "Service Status: $SERVICE_STATUS"
          echo "Running Tasks: $RUNNING_COUNT"
          echo "Deployed Image: ${{ steps.image.outputs.IMAGE_URI }}"
          echo "Commit: ${{ github.sha }}"

